version: '3.7'

services:
  drs-api:
    container_name: drs-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - /var/www/uploads:/var/www/uploads
    ports:
      - 8000:3000
    restart: always
