version: '3.7'

services:
  es01:
    image: 'elastic/elasticsearch:7.10.2'
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - 'es-data-es01:/usr/share/elasticsearch/data'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 250M
        reservations:
          cpus: '0.1'
          memory: 200M

  es02:
    image: 'elastic/elasticsearch:7.10.2'
    ports:
      - 9201:9200
      - 9301:9300
    volumes:
      - 'es-data-es02:/usr/share/elasticsearch/data'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 250M
        reservations:
          cpus: '0.1'
          memory: 200M

  es03:
    image: 'elastic/elasticsearch:7.10.2'
    ports:
      - 9202:9200
      - 9302:9300
    volumes:
      - 'es-data-es03:/usr/share/elasticsearch/data'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 250M
        reservations:
          cpus: '0.1'
          memory: 200M

  kibana:
    image: 'elastic/kibana:7.10.2'
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=["http://es01:9200", "http://es02:9201", "http://es03:9202"]

  mongo0:
    hostname: mongo0
    container_name: mongo0
    image: mongo:latest
    expose:
      - 30000
    ports:
      - 30000:30000
    volumes:
      - 'mongodb_repl_data1:/data/db:z'
    restart: always
    command: '--bind_ip_all --replSet rs0 --port 30000'

  mongo1:
    hostname: mongo1
    container_name: mongo1
    image: mongo:latest
    expose:
      - 30001
    ports:
      - 30001:30001
    volumes:
      - 'mongodb_repl_data2:/data/db:z'
    restart: always
    command: '--bind_ip_all --replSet rs0 --port 30001'

  mongo2:
    hostname: mongo2
    container_name: mongo2
    image: mongo:latest
    expose:
      - 30002
    ports:
      - 30002:30002
    volumes:
      - 'mongodb_repl_data3:/data/db:z'
    restart: always
    command: '--bind_ip_all --replSet rs0 --port 30002'

  redis-starter:
    image: 'redis:6.2-alpine'
    container_name: redis-starter
    restart: always
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    command: /bin/sh -c "redis-server --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81"
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis-starter/data'

  drs-api:
    container_name: drs-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - /var/www/uploads:/var/www/uploads
    depends_on:
      - redis-starter
    ports:
      - 8000:3000
    restart: always

volumes:
  mongodb_repl_data1:
    external: true
  mongodb_repl_data2:
    external: true
  mongodb_repl_data3:
    external: true
  redis_data:
    driver: local
  es-data-es01:
  es-data-es02:
  es-data-es03:
