export enum ActivityLogEvent {
  ACTIVITY_LOG = 'activity.log',
  DOCUMENT_DOWNLOADED = 'document.downloaded',
  DOCUMENT_VIEWED = 'document.viewed',
  DOCUMENT_CREATED = 'document.created',
  DOCUMENT_UPDATED = 'document.updated',
  DOCUMENT_DELETED = 'document.deleted',
}

export enum ActivityAction {
  // Files
  PREVIEW = 'PREVIEW',
  SET_VISIBILITY_PUBLIC = 'SET_VISIBILITY_PUBLIC',
  SET_VISIBILITY_PRIVATE = 'SET_VISIBILITY_PRIVATE',
  RENAME = 'RENAME',

  // Projects
  DEACTIVATED = 'DEACTIVATED',
  UPDATED = 'UPDATED',
  ADD_MEMBER = 'ADD_MEMBER',
  REMOVE_MEMBER = 'REMOVE_MEMBER',
  ADD_MANAGER = 'ADD_MANAGER',
  REMOVE_MANAGER = 'REMOVE_MANAGER',

  // Auth
  PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED = 'PASSWORD_RESET_COMPLETED',
  RESENT_INVITE = 'RESENT_INVITE',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',

  // Notifications (Optional but good to have)
  MARK_ALL_NOTIFICATIONS_READ = 'MARK_ALL_NOTIFICATIONS_READ',
  MARK_NOTIFICATION_READ = 'MARK_NOTIFICATION_READ',

  // Users
  ACTIVATED = 'ACTIVATED',
  VERIFIED = 'VERIFIED',
}
