apiVersion: v1
kind: ConfigMap
metadata:
  name: drs-api-config
  namespace: backend
data:
  DEFAULT_PAGE_SIZE: '10'
  # Redis Config
  REDIS_HOST: 'drs-redis-do-user-16324433-0.c.db.ondigitalocean.com'
  REDIS_PORT: '25061'
  # MAIL Config
  MAIL_FROM: 'noreply@drs.scidar.org'
  MAIL_HOST: 'in-v3.mailjet.com'
  MAIL_PORT: '465'
  MAIL_USER: '5506be9938b4c01b526f396c0a9130be'
  # AWS Config
  AWS_S3_BUCKET: 'scidar-drs-uploads'
  AWS_ACCESS_KEY_ID: 'AKIAVRUVSHAG6QSJU5T2'
  AWS_S3_REGION: 'us-east-1'
  # THROTTLER - RATE LIMITING
  UPLOAD_RATE_TTL: '60'
  UPLOAD_RATE_LIMIT: '3'
  CLIENT_URL: 'https://drs.scidar.org'
