apiVersion: v1
kind: Secret
metadata:
  name: drs-api-secret
  namespace: backend
type: Opaque
data:
  DATABASE_URL: 'bW9uZ29kYitzcnY6Ly9kb2FkbWluOjY0ajE5bFBhM1NrcTg1STdAZHJzLWRiLWRkYzU4ZDhhLm1vbmdvLm9uZGlnaXRhbG9jZWFuLmNvbS9hZG1pbj9hdXRoU291cmNlPWFkbWluJnJlcGxpY2FTZXQ9ZHJzLWRiJnRscz10cnVl'
  SWAGGER_PASSWORD: 'YWRtaW4='
  REDIS_PASS: 'QVZOU19YMm9JenE0WUVYODNSbEhwYlA3'
  MAIL_PASSWORD: 'NjU1NjE5NmMzNmEyYzk4N2Q2MGM2MTU3ODUwMzk2YmQ='
  AWS_SECRET_ACCESS_KEY: 'QU1RbVI2Qno1eDRZaHhpL0FBek54MURHT0hRMnRYOTZVOXNHcm9UQQ=='
